### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by DennisDofferhoff** [XattSPT/io.flic#10]
hi I get the error in Homey saying. Nothing in my setting has changed. Upgrade issue versions?
TypeError: Cannot read property ‘trigger’ of undefined

I followed my own guide which worked fine
https://community.homey.app/t/connect-flic2-hub-buttons-to-homey-with-flic-app/51845

**Comment by XattSPT** [comment]
I’m getting same error and is under investigation.

If you restart the app solves the problem (temporally)

I’ll further investigate the error…

El dl, 29 nov 2021 a les 21:00 DennisDofferhoff ***@***.***>
va escriure:
