### ISSUE TITLE
Homey Pro 23 - max 5 flics can be added

### ISSUE THREAD

**Issue by btoreid** [XattSPT/io.flic#12]
Hi, this could be a local issue, but I have not figured it out. Tried all the normal stuff, restart app, rebooted the Homey ++

![image](https://github.com/XattSPT/io.flic/assets/86227755/f77a41d5-f456-4193-b30a-964d00bab912)

Translated is says that no new devices are found. If I remove one Flic, I can add one more (up to five).

On mye Homey Pro 2019, no such limit is present.

**Comment by dDondero** [comment]
I'm having this issue myself. I have only added two buttons, and it cannot find any of my other buttons. 

I'm using webhooks, so couldn't these simply be virtual buttons? As long as you have three options, they can be mapped with Flic's "Internet request" for single, double and long-press. 

I don't understand where these limitations exist, or why you even need to search for devices.
