### ISSUE TITLE
Flic twist

### ISSUE THREAD

**Issue by ronnyjans** [XattSPT/io.flic#13]
Hi, in a couple of weeks the new Flic Twist and the new Flic Hubs will be available. Can we expect an update shortly after they are released?

**Comment by dDondero** [comment]
I got mine a few weeks back. Hoped that they could be used with Matter, but I read Matter doesn't support incremental up/down, ie. using the dial. Hope that Flic's APIs provide something we can utilize.

**Comment by Feije70** [comment]
Same here, received Flic Twist and hub. Wondering if an update can be expected.

**Comment by XattSPT** [comment]
As far as I know, nowadays is not possble to control twist from sdk. Flic has not released sdk update. It seems they are prioritizing other things (https://community.flic.io/topic/18319/update-sdk-to-use-the-flictwist). Enjoy your big Flic paperweitght.

Once sdk is available, I’ll be first interested to develop it! ;)

**Comment by Feije70** [comment]
Thanks for the heads up! In the meantime I’ll enjoy my Flic paperweight :)
