### ISSUE TITLE
i have flic hub - are you from holland ? 

### ISSUE THREAD

**Issue by mruiter** [XattSPT/io.flic#3]
i can lend it to you for a few weeks if you need one for the implementation ?

**Comment by XattSPT** [comment]
Dear @mruiter ,

   thanks for your kind offering. 

   First public release is pending Athom approval, so I hope it will be available few next days. 

   This first version only works throught phone or hub. 

   I'll try to develop direct connection in future releases. 

Regards,

G.

**Comment by mruiter** [comment]
Direct connection is going to be pretty hard I guess since flic requires a daemon process that sits between the communication and hands out some code . We have tried to implement it before a few years ago .

Verstuurd vanaf mijn iPhone

**Comment by f-aubert** [comment]
Was it implemented? Are you still working on the app? I'm looking for small buttons for homey without needing yet another bridge / hub. Thanks for your great work @XattSPT

**Comment by XattSPT** [comment]
No.
