### ISSUE TITLE
Nothing happens when webhook is called

### ISSUE THREAD

**Issue by relnah** [XattSPT/io.flic#8]
Get OR Post to https://webhooks.athom.com/webhook/xxxxxxxxxxxxxxxxxxxxxxxxxxx/?id=xxxxxxxxx&action=click&flic=1
does nothing. Trying from Insomnia and get "ok" back, but nothing happens in Homey.

homeyVersion | "7.1.5"
homeyModelId | "homey3d"
homeyModelName | "Homey Pro (Early 2019)"

**Comment by XattSPT** [comment]
Are u copying url from flic advance ajustments?

El dl, 1 nov 2021 a les 19:29 relnah ***@***.***> va escriure:

**Comment by relnah** [comment]
Yes. The x:es are ofcourse real ids in my real url. I used the https://my.homey.app/ webpage to copy it on my computer and test it. To make sure I got it copied correctly.

Edit: If I send request with bad IDs I get a 404 back. So URL seems copied correctly since I get 200 back and an ok in body.

**Comment by XattSPT** [comment]
Mmmm…

Have you configured a flow on click on your flic 1 on homey app?

Have you copied this url to your flic app, as http request? I supose you
have a flic hub, rigth?

If every point is doubled checked you can try to restart app on homey,
sometimes your id is not cached at first start.

If doesn’t work, delete and install again app on homey.



El dl, 1 nov 2021 a les 22:22 relnah ***@***.***> va escriure:

**Comment by relnah** [comment]
Restarting app worked! :)
Before creating this issue I had double checked and re-installed the app. But never restarted it.
Thanks for quick replies!
