### ISSUE TITLE
Am I doing this wrong?

### ISSUE THREAD

**Issue by Idus** [XattSPT/io.flic#9]
I currently have five flic-buttons installed on my Flic Hub.

But when I try to add a device (stating "using Flic hub or Phone") - I only get one button to choose from. No relevance to the names on the Flic-hub or anything else. :-(

I would prefer "Homey -- Flic Hub -- Flic Button" - but is this some "Homey -- Flic Button" thing?

Cheers and thank you for your time and effort! :)

**Comment by XattSPT** [comment]
Yes, you should add them one by one, and then config on flic app or flic hub

When its configured on first push, flic name is sent to homey



El dg, 7 nov 2021 a les 18:17 Idus ***@***.***> va escriure:
